//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.12 at 02:50:37 PM CST 
//


package com.yash.iot.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.yash.iot.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WarehouseBinSensorDataRequest_QNAME = new QName("http://www.example.org/WarehouseBinSensorDataRequest", "WarehouseBinSensorDataRequest");
    private final static QName _WarehouseBinSensorDataResponse_QNAME = new QName("http://www.example.org/WarehouseBinSensorDataRequest", "WarehouseBinSensorDataResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.yash.iot.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WarehouseBinSensorDataRequest }
     * 
     */
    public WarehouseBinSensorDataRequest createWarehouseBinSensorDataRequest() {
        return new WarehouseBinSensorDataRequest();
    }

    /**
     * Create an instance of {@link WarehouseBinSensorDataResponse }
     * 
     */
    public WarehouseBinSensorDataResponse createWarehouseBinSensorDataResponse() {
        return new WarehouseBinSensorDataResponse();
    }

    /**
     * Create an instance of {@link BinSensorDataRecord }
     * 
     */
    public BinSensorDataRecord createBinSensorDataRecord() {
        return new BinSensorDataRecord();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WarehouseBinSensorDataRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/WarehouseBinSensorDataRequest", name = "WarehouseBinSensorDataRequest")
    public JAXBElement<WarehouseBinSensorDataRequest> createWarehouseBinSensorDataRequest(WarehouseBinSensorDataRequest value) {
        return new JAXBElement<WarehouseBinSensorDataRequest>(_WarehouseBinSensorDataRequest_QNAME, WarehouseBinSensorDataRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WarehouseBinSensorDataResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/WarehouseBinSensorDataRequest", name = "WarehouseBinSensorDataResponse")
    public JAXBElement<WarehouseBinSensorDataResponse> createWarehouseBinSensorDataResponse(WarehouseBinSensorDataResponse value) {
        return new JAXBElement<WarehouseBinSensorDataResponse>(_WarehouseBinSensorDataResponse_QNAME, WarehouseBinSensorDataResponse.class, null, value);
    }

}
